js/forum/src/addComposerAutocomplete.js
js/forum/src/addMentionedByList.js
js/forum/src/addPostReplyAction.js
js/forum/src/components/PostMentionedNotification.js
js/forum/src/components/UserMentionedNotification.js
js/forum/src/main.js

See [flarum/core #265](https://github.com/flarum/core/issues/265).
- Adjusts key names to three-tier namespacing.
- Extracts previously unextracted strings.
- Changes an instance of `punctuate` to `punctuateSeries`.
- Modifies the syntax of **addMentionedByLIst.js** slightly.

Reorganize key names

---

js/forum/src/addPostReplyAction.js

fixes https://github.com/flarum/core/issues/781
The issue where newlines are added to the composer on mentioning even if composer is empty.

unnecessary newlines with empty composer

---

js/forum/dist/extension.js
js/forum/src/addMentionedByList.js

In Dutch: "Jij hebt" / "Someuser HEEFT" -> _self text was ignored, comparing POST with USER object.
Combines with [this pull request in Dutch translation](https://github.com/rodymol123/flarum-ext-dutch/pull/14)

Fix: Someuser vs. You (mention) -- In English: the same. 

---

js/forum/Gulpfile.js
js/forum/bower.json
js/forum/package.json

Given the only bower dependency is also available in npm, I suggest we drop bower and require that package through npm.
This will reduce the number of commands required to setup the project as well as prevent errors like *not installing* the bower dependencies #25 
These changes have no impact on the resulting `extension.js`.

Drop bower usage and go full npm

---

js/forum/dist/extension.js
js/forum/src/utils/selectedText.js

As reported here https://discuss.flarum.org/d/5966-allow-image-in-quote images are not kept when quoting a post. In fact everything apart from emojis was simply converted to plain text.
I added support for images and links by reverting the preview html back to markdown when quoting.
You can now quote emojis, images and links, including images and emojis inside links.
PS: the dist file changed a lot more, I guess you made updates to the `flarum-gulp` since the last mentions update...

Keep images and links when quoting

---

src/ConfigureMentions.php

`_` is special character in mysql so like query was fetching different result for user who's unsername starts with or contains `_`

Replace underscore with backslash and underscore 

---

src/ConfigureMentions.php

Fixes flarum/core#1956 - ErrorException: Trying to get property 'display_name' of 
non-object. ConfigureMentions::addPostId method set mention details 
based on if there was an existing post. This caused an error if there 
was an existing post, but the user who posted had been deleted. The 
mention details are now only set if there is a user associated with the 
post being mentioned.

fix: Determine if a post has a user before setting mention details

---

src/Listener/UpdateMentionsMetadataWhenVisible.php

When combining the mention extension with the Private Discussion extension, it is possible to notify the author of a mentioned post of the contents of a private discussion that contains the quoted text.
Steps to reproduce:
1. Log in as User A, create a discussion
2. Log in as User B, go to discussion from point 1, quote the post.
3. Copy this quote and start a new discussion, set recipients to someone other than user A (e.g. user C), thus creating a Private Discussion without User A.
4. User A gets notified that they have been mentioned in discussion from point 4, even if they do not have access to it.
The change doesn't use the PD code, rather it utilises the existing visibility mechanism which I feel is much cleaner, not coupled with PD and has the potential to resolve issues with any …

Check reply with mention can be read by original poster

---

js/src/forum/addMentionedByList.js

Previously, if there was a single reply and it was adjacent to the post it wasn't shown.
See discussion on Discuss: https://discuss.flarum.org/d/23666-flarum-010-beta13-released/75

Always show replies list on posts

---

js/src/forum/addComposerAutocomplete.js

- Cache the order in which users are returned by the API to stop the mentions list from jumping around
- Only ping the api when 2 or more characters are entered

Stop mentions dropdown from jumping around

---

src/Notification/PostMentionedBlueprint.php
src/Notification/UserMentionedBlueprint.php
views/emails/postMentioned.blade.php
views/emails/userMentioned.blade.php

Depends on https://github.com/flarum/core/pull/2244
Ref https://github.com/flarum/core/issues/1934
The "near" parameter is not generated through the url generator because, for some reason, that didn't work in testing. Which is something to investigate later, but not immediately relevant to this PR.

Translate notification emails

---

src/Notification/PostMentionedBlueprint.php
views/emails/postMentioned.blade.php

Using beta.15:
A postmention email notification incorrectly displays the `post` display_name, rather than the `reply` display_name:

Incorrect display_name showing in email notifications

---

src/FilterVisiblePosts.php

**Part of flarum/core#2637**
`mentionedBy` is accessed in the same class a little below but not eager loaded, additionally we want to only eager load relations that weren't loaded before, otherwise it can end up forgetting about the previously eager loaded relations.

Eager load mentionedBy and only missing relations

---

extend.php
js/admin.js
js/src/admin/index.js
js/src/forum/addComposerAutocomplete.js
js/src/forum/addPostMentionPreviews.js
js/src/forum/utils/cleanDisplayName.js
js/src/forum/utils/reply.js
js/src/forum/utils/textFormatter.js
less/forum.less
locale/en.yml
migrations/2021_04_19_000000_set_default_settings.php
src/ConfigureMentions.php
src/Formatter/FormatPostMentions.php
src/Formatter/FormatUserMentions.php
src/Formatter/UnparsePostMentions.php
src/Formatter/UnparseUserMentions.php
tests/integration/api/PostMentionsTest.php
tests/integration/api/UserMentionsTest.php

**Part of flarum/core#1734**
**Works with flarum/core#2780**
**Changes proposed in this pull request:**
* Changes the mentions format:
+ From `@Username` to `@"Display Name"#USER_ID` for user mentions.
+ From `@Username#POST_ID` to `@"Display Name"#pPOST_ID` for post mentions.
* Updates old formats and old mention data by hooking into the unparsing and rendering processes updating tags:
1. For **unparsing** and **rendering** it first updates mention tags to hold newer data, for example `USERMENTION` tags containing old display names or slugs.
2. For **unparsing** it then transforms mention tags to raw mention formats, for example: `<USERMENTION displayname="Display Name" id="ID">@Username</USERMENTION>` becomes `@"Display Name"#ID`.
3. Step 1 above results in hiding deleted user …

New mentions format, decouple usernames from mentions

---

tests/integration/api/PostMentionsTest.php
tests/integration/api/UserMentionsTest.php

Updates tests to be compatible with `flarum/testing`.
In `flarum/testing`, `UsesSettings` trait was removed in favor of a better functioning `setting()` method.

Update tests to use setting method

---

js/src/forum/addComposerAutocomplete.js
src/ConfigureMentions.php
tests/integration/api/PostMentionsTest.php
tests/integration/api/UserMentionsTest.php

**Fixes flarum/core#2879**
Adds support for smart quotes in mentions format.
When testing don't forget to clear the cache first `php flarum cache:clear`.

Support smart quotes in mentions format

---

extend.php
src/FilterVisiblePosts.php

**Fixes flarum/core#3047**
**Relies on flarum/core#3048**
These missing relations caused more queries to be called, the more mentions posts have the more queries produced.
Before | After
-- | --
With all included relations (notably `firstPost,lastPost` containing post and user mentions)
Before | After
-- | --
Before | After
-- | --
Before | After
-- | --

Eager load more necessary related mentions

---

extend.php
src/Listener/UpdateMentionsMetadataWhenVisible.php

**Fixes flarum/core#2989**
The reason this happens is because the modified relationship is not refreshed, so the formatter doesn't recognize the new mentions as valid, and the returned HTML content contains the unproperly rendered mentions.

Fix unrecognised user/post mentions

---

js/src/forum/addComposerAutocomplete.js

Closes https://github.com/flarum/core/issues/3070
If the user doesn't have permission to search users, there will currently be browser errors, as the current implementation will still attempt to search and autocomplete. In this PR, we check for permission before searching. The dropdown will still support autocomplete of users currently participating in the discussion.

Only search users via rest API if user has permission

---

js/src/forum/addComposerAutocomplete.js

**Changes proposed in this pull request:**
Re-using the TextEditor outside of the composer causes errors, as this extension attempts to access `app.composer` instead of `this.attrs.composer`.
**Necessity**
**Confirmed**

fix: autocomplete errors with TextEditor re-use

---

js/src/forum/compat.js
js/src/forum/index.js
js/src/forum/utils/reply.js

**Changes proposed in this pull request:**
Added compat exports and extensibility.
**Reviewers should focus on:**
Check that nothing is broken.
**Necessity**
**Confirmed**

Added compat exports and extensibility

---

src/Formatter/FormatUserMentions.php
src/Formatter/UnparseUserMentions.php

**Fixes [#2902](https://github.com/flarum/core/issues/2902)**
**Changes proposed in this pull request:**
Extensions such as `askvortsov/flarum-moderator-warnings`, `fof/pages` and `fof/moderator-notes` allow for mentioning a user outside of a `Post`. This functionality was broken in the `1.0` release due to pulling the user directly from the post relationship.
This is an interim solution, first proposed by @datitisev in #2902, until the refactor of the `Formatter` API.
I added `&& $post->exists` to the conditional proposed in the issue, as this maintains the current expectation of extensions using the formatter in this way (ie passing `new Post()` to the renderer.
Examples: 
https://github.com/FriendsOfFlarum/moderator-notes/blob/7496beb5abcdec2c2a48505c1c05dc4343831548/src/Api/Serializer/ …

fix?: Allow mentions from non-post objects
